// BDO Processing recipes — comprehensive category-based input→output conversions
// Quantities are per single processing action (base yield before mastery)

// ── Dried Fish → Arsha.io item IDs (for marketplace price lookup) ──
export const DRIED_FISH_IDS = {
  'Dried Mudskipper': 8501, 'Dried Tuna': 8502, 'Dried Beltfish': 8503,
  'Dried Flounder': 8504, 'Dried Salmon': 8505, 'Dried Amberjack': 8506,
  'Dried Porgy': 8507, 'Dried Swellfish': 8508, 'Dried Saurel': 8509,
  'Dried Rockfish': 8510, 'Dried Squid': 8511, 'Dried Octopus': 8512,
  'Dried Crab': 8513, 'Dried Jellyfish': 8514, 'Dried Shellfish': 8515,
  'Dried Carp': 8516, 'Dried Crucian Carp': 8517, 'Dried Trout': 8518,
  'Dried Catfish': 8519, 'Dried Freshwater Eel': 8520, 'Dried Snakehead': 8521,
  'Dried Cherry Salmon': 8522, 'Dried Cuvier': 8523, 'Dried Sunfish': 8524,
  'Dried Sea Bass': 8525, 'Dried Angler': 8526, 'Dried Swordfish': 8527,
  'Dried Mackerel': 8528, 'Dried Flying Fish': 8529, 'Dried Skipjack': 8530,
  'Dried Ray': 8531, 'Dried Seahorse': 8532, 'Dried Starfish': 8533,
  'Dried Filefish': 8534, 'Dried Scorpion Fish': 8535, 'Dried Mullet': 8536,
  'Dried Swiri': 8537, 'Dried Sturgeon': 8538, 'Dried Piranha': 8539,
  'Dried Mandarin Fish': 8540, 'Dried Lenok': 8541, 'Dried Arowana': 8542,
  'Dried Sweetfish': 8543, 'Dried Terrapin': 8544, 'Dried Bass': 8545,
  'Dried Crawfish': 8546, 'Dried Dace': 8547, 'Dried Bluegill': 8548,
  'Dried Perch': 8549, 'Dried Notch Jaw': 8550, 'Dried Mudfish': 8551,
  'Dried Goby Minnow': 8552, 'Dried Bitterling': 8553, 'Dried Bleeker': 8554,
  'Dried Yellow Fin Sculpin': 8555, 'Dried Cero': 8556, 'Dried Sea Eel': 8557,
  'Dried Croaker': 8558, 'Dried Greenling': 8559, 'Dried Flatfish': 8560,
  'Dried Grunt': 8561, 'Dried Herring': 8562, 'Dried Sardine': 8563,
  'Dried Round Herring': 8564, 'Dried Silver Stripe Round Herring': 8565,
  'Dried Whiting': 8566, 'Dried Dolphinfish': 8567, 'Dried Striped Catfish': 8568,
  'Dried Gunnel': 8569, 'Dried Golden-Thread': 8570, 'Dried Butterflyfish': 8601,
  'Dried Clownfish': 8602, 'Dried Blue Tang': 8603, 'Dried Checkerboard Wrasse': 8604,
  'Dried Pomfret': 8605, 'Dried Moray': 8629, 'Dried Tilefish': 8630,
  'Dried Porcupine Fish': 8631, 'Dried Tongue Sole': 8632, 'Dried Atka Mackerel': 8633,
  'Dried Cuttlefish': 8634, 'Dried Mackerel Pike': 8635, 'Dried Horn Fish': 8636,
  'Dried Dollarfish': 8637, 'Dried Sandeel': 8638, 'Dried Spotted Barbel': 8639,
  'Dried Miho Spine Loach': 8640, 'Dried Diamond Minnow': 8641,
  'Dried Sandfish': 8582, 'Dried Rosefish': 8583, 'Dried Grouper': 8584,
  'Dried Bigeye': 8585, 'Dried Fourfinger Threadfin': 8586,
  'Dried Leather Carp': 8587, 'Dried Striped Shiner': 8588,
  'Dried Soho Bitterling': 8590, 'Dried Bubble Eye': 8591, 'Dried Pacu': 8592,
  'Dried Yellow-Head Catfish': 8593, 'Dried Smelt': 8594,
  'Dried Rosy Bitterling': 8595, 'Dried Roundtail Paradisefish': 8596,
  'Dried Grayling': 8597, 'Dried Tapertail Anchovy': 8598,
  'Dried Kuhlia Marginata': 8599, 'Dried Rock Hind': 8600,
  'Dried Nibbler': 8571, 'Dried Siganid': 8572, 'Dried Bluefish': 8573,
  'Dried Surfperch': 8574, 'Dried Blackfin Sweeper': 8575,
  'Dried Smokey Chromis': 8576, 'Dried Maomao': 8577, 'Dried Pintado': 8578,
  'Dried Gurnard': 8579, 'Dried John Dory': 8581, 'Dried Minnow': 8648,
  'Dried Snapper': 8585, 'Dried Gizzard Shad': 8585,
  'Dried Pirarucu': 8592, 'Dried Pike': 8549,
  'Dried Shrimp': 8515, 'Dried Abalone': 8515,
  'Dried Eel': 8520, 'Dried Sea Perch': 8510,
  'Dried Giant Octopus': 8512, 'Dried Sea Horse': 8532,
  'Dried Diamond Starfish': 8533,
};

// ── Raw fish NPC vendor sell prices (silver) — the "trade price" of unprocessed fish ──
// Grouped by fish grade: White ~500-1500, Green ~2000-5000, Blue ~8000-25000, Yellow ~25000-80000, Orange ~80000-200000
export const FISH_VENDOR_PRICES = {
  // White grade
  'Mudskipper': 500, 'Jellyfish': 500, 'Starfish': 500, 'Shellfish': 500,
  'Surfperch': 500, 'Fourfinger Threadfin': 500, 'Scorpion Fish': 500,
  'Soho Bitterling': 500, 'Bubble Eye': 500, 'Rosefish': 500,
  'Round Herring': 500, 'Silver Stripe Round Herring': 500, 'Whiting': 500,
  'Sandeel': 500, 'Mackerel Pike': 500, 'Tongue Sole': 500, 'Sandfish': 500,
  'Dace': 500, 'Notch Jaw': 500, 'Goby Minnow': 500, 'Bleeker': 500,
  'Rock Hind': 500, 'Butterflyfish': 500, 'Rosy Bitterling': 500,
  'Roundtail Paradisefish': 500, 'Saurel': 500,
  // Green grade
  'Filefish': 2000, 'Mullet': 2000, 'Seahorse': 2000, 'Crab': 2000,
  'Flatfish': 2000, 'Perch': 2000, 'Crucian Carp': 2000, 'Starfish': 2000,
  'Bitterling': 2000, 'Greenling': 2000, 'Gurnard': 2000, 'Blackfin Sweeper': 2000,
  'Shrimp': 2000, 'Minnow': 2000, 'Stickleback': 2000,
  'Striped Catfish': 2000, 'Gunnel': 2000, 'Clownfish': 2000,
  'Dolphinfish': 2000, 'Kuhlia Marginata': 2000, 'Spotted Barbel': 2000,
  // Blue grade
  'Salmon': 5000, 'Flounder': 5000, 'Amberjack': 5000, 'Beltfish': 5000,
  'Rockfish': 5000, 'Squid': 5000, 'Mackerel': 5000, 'Flying Fish': 5000,
  'Skipjack': 5000, 'Ray': 5000, 'Trout': 5000, 'Catfish': 5000,
  'Bass': 5000, 'Crawfish': 5000, 'Sweetfish': 5000, 'Terrapin': 5000,
  'Mudfish': 5000, 'Bluefish': 5000, 'Sardine': 5000, 'Croaker': 5000,
  'Cuttlefish': 5000, 'Horn Fish': 5000, 'Dollarfish': 5000, 'Bigeye': 5000,
  'Smelt': 5000, 'Grayling': 5000, 'Blue Tang': 5000, 'Pintado': 5000,
  'Atka Mackerel': 5000, 'Abalone': 5000, 'Yellow Fin Sculpin': 8000,
  'Cherry Salmon': 8000, 'Lenok': 8000, 'Arowana': 8000,
  'Freshwater Eel': 8000, 'Sea Eel': 8000, 'Striped Shiner': 8000,
  'Gizzard Shad': 5000, 'Sea Perch': 5000, 'Combfish': 5000,
  'Winding Fish': 5000, 'Eel': 5000, 'Pike': 5000,
  // Yellow grade
  'Snakehead': 25000, 'Cuvier': 25000, 'Sunfish': 25000, 'Sea Bass': 25000,
  'Angler': 15000, 'Swordfish': 15000, 'Swellfish': 15000, 'Carp': 15000,
  'Sturgeon': 25000, 'Piranha': 20000, 'Mandarin Fish': 25000,
  'Siganid': 15000, 'Smokey Chromis': 25000, 'Maomao': 15000,
  'John Dory': 15000, 'Grouper': 15000, 'Leather Carp': 20000,
  'Pacu': 15000, 'Yellow-Head Catfish': 15000, 'Tapertail Anchovy': 15000,
  'Checkerboard Wrasse': 15000, 'Moray': 15000, 'Tilefish': 25000,
  'Porcupine Fish': 15000, 'Pomfret': 8000, 'Miho Spine Loach': 15000,
  'Diamond Minnow': 15000, 'Golden-Thread': 15000, 'Cero': 15000,
  'Golden Siniperca': 25000, 'Snapper': 15000, 'Marlin': 25000,
  'Monk Fish': 15000, 'Pirarucu': 15000, 'Luvar': 15000, 'Tanbager': 15000,
  'Gourami': 15000, 'Diamond Starfish': 15000, 'Sea Trumpet': 15000,
  // Orange grade
  'Tuna': 80000, 'Porgy': 80000, 'Grunt': 80000, 'Nibbler': 80000,
  'Swiri': 80000, 'Whale Shark': 100000, 'Yellowfin Tuna': 80000,
  'King Archelon': 80000, 'Giant Octopus': 80000, 'Hare': 80000,
};

export const PROCESSING_CATEGORIES = [
  'Heating', 'Grinding', 'Chopping', 'Drying', 'Filtering', 'Shaking', 'Simple Cooking', 'Simple Alchemy',
];

export const PROCESSING_RECIPES = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // HEATING — Ore → Melted Shard (5 ore → 1-4 shard, avg ~2.5)
  // ═══════════════════════════════════════════════════════════════════════════════
  { category: 'Heating', name: 'Copper Ore → Melted Copper Shard', inputs: [{ name: 'Copper Ore', qty: 5 }], outputs: [{ name: 'Melted Copper Shard', qty: 2 }] },
  { category: 'Heating', name: 'Iron Ore → Melted Iron Shard', inputs: [{ name: 'Iron Ore', qty: 5 }], outputs: [{ name: 'Melted Iron Shard', qty: 2 }] },
  { category: 'Heating', name: 'Tin Ore → Melted Tin Shard', inputs: [{ name: 'Tin Ore', qty: 5 }], outputs: [{ name: 'Melted Tin Shard', qty: 2 }] },
  { category: 'Heating', name: 'Lead Ore → Melted Lead Shard', inputs: [{ name: 'Lead Ore', qty: 5 }], outputs: [{ name: 'Melted Lead Shard', qty: 2 }] },
  { category: 'Heating', name: 'Zinc Ore → Melted Zinc Shard', inputs: [{ name: 'Zinc Ore', qty: 5 }], outputs: [{ name: 'Melted Zinc Shard', qty: 2 }] },
  { category: 'Heating', name: 'Silver Ore → Melted Silver Shard', inputs: [{ name: 'Silver Ore', qty: 5 }], outputs: [{ name: 'Melted Silver Shard', qty: 2 }] },
  { category: 'Heating', name: 'Gold Ore → Melted Gold Shard', inputs: [{ name: 'Gold Ore', qty: 5 }], outputs: [{ name: 'Melted Gold Shard', qty: 2 }] },
  { category: 'Heating', name: 'Platinum Ore → Melted Platinum Shard', inputs: [{ name: 'Platinum Ore', qty: 5 }], outputs: [{ name: 'Melted Platinum Shard', qty: 2 }] },
  { category: 'Heating', name: 'Titanium Ore → Melted Titanium Shard', inputs: [{ name: 'Titanium Ore', qty: 5 }], outputs: [{ name: 'Melted Titanium Shard', qty: 2 }] },
  { category: 'Heating', name: 'Vanadium Ore → Melted Vanadium Shard', inputs: [{ name: 'Vanadium Ore', qty: 5 }], outputs: [{ name: 'Melted Vanadium Shard', qty: 2 }] },
  { category: 'Heating', name: 'Mythril Ore → Melted Mythril Shard', inputs: [{ name: 'Mythril Ore', qty: 5 }], outputs: [{ name: 'Melted Mythril Shard', qty: 2 }] },

  // HEATING — Melted Shard → Ingot (10 shard → 1-4 ingot, avg ~2.5)
  { category: 'Heating', name: 'Melted Copper Shard → Copper Ingot', inputs: [{ name: 'Melted Copper Shard', qty: 10 }], outputs: [{ name: 'Copper Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Iron Shard → Iron Ingot', inputs: [{ name: 'Melted Iron Shard', qty: 10 }], outputs: [{ name: 'Iron Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Tin Shard → Tin Ingot', inputs: [{ name: 'Melted Tin Shard', qty: 10 }], outputs: [{ name: 'Tin Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Lead Shard → Lead Ingot', inputs: [{ name: 'Melted Lead Shard', qty: 10 }], outputs: [{ name: 'Lead Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Zinc Shard → Zinc Ingot', inputs: [{ name: 'Melted Zinc Shard', qty: 10 }], outputs: [{ name: 'Zinc Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Silver Shard → Silver Ingot', inputs: [{ name: 'Melted Silver Shard', qty: 10 }], outputs: [{ name: 'Silver Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Gold Shard → Gold Ingot', inputs: [{ name: 'Melted Gold Shard', qty: 10 }], outputs: [{ name: 'Gold Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Platinum Shard → Platinum Ingot', inputs: [{ name: 'Melted Platinum Shard', qty: 10 }], outputs: [{ name: 'Platinum Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Titanium Shard → Titanium Ingot', inputs: [{ name: 'Melted Titanium Shard', qty: 10 }], outputs: [{ name: 'Titanium Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Vanadium Shard → Vanadium Ingot', inputs: [{ name: 'Melted Vanadium Shard', qty: 10 }], outputs: [{ name: 'Vanadium Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Melted Mythril Shard → Mythril Ingot', inputs: [{ name: 'Melted Mythril Shard', qty: 10 }], outputs: [{ name: 'Mythril Ingot', qty: 2 }] },

  // HEATING — Alloys
  { category: 'Heating', name: 'Brass Ingot (Copper + Zinc)', inputs: [{ name: 'Melted Copper Shard', qty: 5 }, { name: 'Melted Zinc Shard', qty: 5 }], outputs: [{ name: 'Brass Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Bronze Ingot (Copper + Tin)', inputs: [{ name: 'Melted Copper Shard', qty: 5 }, { name: 'Melted Tin Shard', qty: 5 }], outputs: [{ name: 'Bronze Ingot', qty: 2 }] },
  { category: 'Heating', name: 'Steel (Iron + Coal)', inputs: [{ name: 'Melted Iron Shard', qty: 5 }, { name: 'Coal', qty: 5 }], outputs: [{ name: 'Steel', qty: 2 }] },

  // HEATING — Pure Crystals (Skilled heating)
  { category: 'Heating', name: 'Pure Iron Crystal', inputs: [{ name: 'Metal Solvent', qty: 2 }, { name: 'Iron Ingot', qty: 3 }], outputs: [{ name: 'Pure Iron Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Copper Crystal', inputs: [{ name: 'Metal Solvent', qty: 2 }, { name: 'Copper Ingot', qty: 3 }], outputs: [{ name: 'Pure Copper Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Lead Crystal', inputs: [{ name: 'Metal Solvent', qty: 2 }, { name: 'Lead Ingot', qty: 3 }], outputs: [{ name: 'Pure Lead Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Tin Crystal', inputs: [{ name: 'Metal Solvent', qty: 2 }, { name: 'Tin Ingot', qty: 3 }], outputs: [{ name: 'Pure Tin Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Zinc Crystal', inputs: [{ name: 'Metal Solvent', qty: 2 }, { name: 'Zinc Ingot', qty: 3 }], outputs: [{ name: 'Pure Zinc Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Silver Crystal', inputs: [{ name: 'Metal Solvent', qty: 1 }, { name: 'Silver Ingot', qty: 3 }], outputs: [{ name: 'Pure Silver Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Gold Crystal', inputs: [{ name: 'Metal Solvent', qty: 1 }, { name: 'Gold Ingot', qty: 3 }], outputs: [{ name: 'Pure Gold Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Platinum Crystal', inputs: [{ name: 'Metal Solvent', qty: 1 }, { name: 'Platinum Ingot', qty: 3 }], outputs: [{ name: 'Pure Platinum Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Mythril Crystal', inputs: [{ name: 'Metal Solvent', qty: 1 }, { name: 'Mythril Ingot', qty: 3 }], outputs: [{ name: 'Pure Mythril Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Titanium Crystal', inputs: [{ name: 'Metal Solvent', qty: 2 }, { name: 'Titanium Ingot', qty: 3 }], outputs: [{ name: 'Pure Titanium Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Pure Vanadium Crystal', inputs: [{ name: 'Metal Solvent', qty: 2 }, { name: 'Vanadium Ingot', qty: 3 }], outputs: [{ name: 'Pure Vanadium Crystal', qty: 1 }] },

  // HEATING — Sturdy Plywood
  { category: 'Heating', name: 'Sturdy Ash Plywood', inputs: [{ name: 'Ash Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy Ash Plywood', qty: 1 }] },
  { category: 'Heating', name: 'Sturdy Birch Plywood', inputs: [{ name: 'Birch Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy Birch Plywood', qty: 1 }] },
  { category: 'Heating', name: 'Sturdy Cedar Plywood', inputs: [{ name: 'Cedar Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy Cedar Plywood', qty: 1 }] },
  { category: 'Heating', name: 'Sturdy Fir Plywood', inputs: [{ name: 'Fir Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy Fir Plywood', qty: 1 }] },
  { category: 'Heating', name: 'Sturdy Maple Plywood', inputs: [{ name: 'Maple Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy Maple Plywood', qty: 1 }] },
  { category: 'Heating', name: 'Sturdy Pine Plywood', inputs: [{ name: 'Pine Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy Pine Plywood', qty: 1 }] },
  { category: 'Heating', name: 'Sturdy White Cedar Plywood', inputs: [{ name: 'White Cedar Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy White Cedar Plywood', qty: 1 }] },
  { category: 'Heating', name: 'Sturdy Acacia Plywood', inputs: [{ name: 'Acacia Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy Acacia Plywood', qty: 1 }] },
  { category: 'Heating', name: 'Sturdy Palm Plywood', inputs: [{ name: 'Palm Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy Palm Plywood', qty: 1 }] },
  { category: 'Heating', name: 'Sturdy Elder Tree Plywood', inputs: [{ name: 'Elder Tree Plywood', qty: 10 }, { name: 'Plywood Hardener', qty: 3 }], outputs: [{ name: 'Sturdy Elder Tree Plywood', qty: 1 }] },

  // HEATING — Thread/Yarn
  { category: 'Heating', name: 'Cotton → Cotton Yarn', inputs: [{ name: 'Cotton', qty: 5 }], outputs: [{ name: 'Cotton Yarn', qty: 2 }] },
  { category: 'Heating', name: 'Flax → Flax Thread', inputs: [{ name: 'Flax', qty: 5 }], outputs: [{ name: 'Flax Thread', qty: 2 }] },
  { category: 'Heating', name: 'Fleece → Knitting Yarn', inputs: [{ name: 'Fleece', qty: 5 }], outputs: [{ name: 'Knitting Yarn', qty: 2 }] },
  { category: 'Heating', name: 'Silkworm Cocoon → Silk Thread', inputs: [{ name: 'Silkworm Cocoon', qty: 5 }], outputs: [{ name: 'Silk Thread', qty: 2 }] },

  // HEATING — Gem Crystals
  { category: 'Heating', name: 'Rough Black Crystal → Black Crystal', inputs: [{ name: 'Rough Black Crystal', qty: 5 }], outputs: [{ name: 'Black Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Rough Red Crystal → Red Crystal', inputs: [{ name: 'Rough Red Crystal', qty: 5 }], outputs: [{ name: 'Red Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Rough Blue Crystal → Blue Crystal', inputs: [{ name: 'Rough Blue Crystal', qty: 5 }], outputs: [{ name: 'Blue Crystal', qty: 1 }] },
  { category: 'Heating', name: 'Rough Green Crystal → Green Crystal', inputs: [{ name: 'Rough Green Crystal', qty: 5 }], outputs: [{ name: 'Green Crystal', qty: 1 }] },

  // HEATING — Misc
  { category: 'Heating', name: 'Rough Stone → Black Stone Powder', inputs: [{ name: 'Rough Stone', qty: 2 }], outputs: [{ name: 'Black Stone Powder', qty: 1 }] },
  { category: 'Heating', name: 'Coal → Processed Coal', inputs: [{ name: 'Coal', qty: 5 }], outputs: [{ name: 'Processed Coal', qty: 2 }] },
  { category: 'Heating', name: 'Bottle of River Water → Distilled Water', inputs: [{ name: 'Bottle of River Water', qty: 1 }], outputs: [{ name: 'Distilled Water', qty: 2 }] },

  // ═══════════════════════════════════════════════════════════════════════════════
  // CHOPPING — Timber → Plank (5 timber → 1-4 plank, avg ~2.5)
  // ═══════════════════════════════════════════════════════════════════════════════
  { category: 'Chopping', name: 'Ash Timber → Ash Plank', inputs: [{ name: 'Ash Timber', qty: 5 }], outputs: [{ name: 'Ash Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Birch Timber → Birch Plank', inputs: [{ name: 'Birch Timber', qty: 5 }], outputs: [{ name: 'Birch Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Cedar Timber → Cedar Plank', inputs: [{ name: 'Cedar Timber', qty: 5 }], outputs: [{ name: 'Cedar Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Fir Timber → Fir Plank', inputs: [{ name: 'Fir Timber', qty: 5 }], outputs: [{ name: 'Fir Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Maple Timber → Maple Plank', inputs: [{ name: 'Maple Timber', qty: 5 }], outputs: [{ name: 'Maple Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Pine Timber → Pine Plank', inputs: [{ name: 'Pine Timber', qty: 5 }], outputs: [{ name: 'Pine Plank', qty: 2 }] },
  { category: 'Chopping', name: 'White Cedar Timber → White Cedar Plank', inputs: [{ name: 'White Cedar Timber', qty: 5 }], outputs: [{ name: 'White Cedar Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Acacia Timber → Acacia Plank', inputs: [{ name: 'Acacia Timber', qty: 5 }], outputs: [{ name: 'Acacia Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Palm Timber → Palm Plank', inputs: [{ name: 'Palm Timber', qty: 5 }], outputs: [{ name: 'Palm Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Elder Tree Timber → Elder Tree Plank', inputs: [{ name: 'Elder Tree Timber', qty: 5 }], outputs: [{ name: 'Elder Tree Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Thorn Tree Timber → Thorn Tree Plank', inputs: [{ name: 'Thorn Tree Timber', qty: 5 }], outputs: [{ name: 'Thorn Tree Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Snowfield Cedar Timber → Snowfield Cedar Plank', inputs: [{ name: 'Snowfield Cedar Timber', qty: 5 }], outputs: [{ name: 'Snowfield Cedar Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Moss Tree Timber → Moss Tree Plank', inputs: [{ name: 'Moss Tree Timber', qty: 5 }], outputs: [{ name: 'Moss Tree Plank', qty: 2 }] },
  { category: 'Chopping', name: 'Thornwood Timber → Thornwood Plank', inputs: [{ name: 'Thornwood Timber', qty: 5 }], outputs: [{ name: 'Thornwood Plank', qty: 2 }] },

  // CHOPPING — Plank → Plywood (10 plank → 1-4 plywood, avg ~2.5)
  { category: 'Chopping', name: 'Ash Plank → Ash Plywood', inputs: [{ name: 'Ash Plank', qty: 10 }], outputs: [{ name: 'Ash Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Birch Plank → Birch Plywood', inputs: [{ name: 'Birch Plank', qty: 10 }], outputs: [{ name: 'Birch Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Cedar Plank → Cedar Plywood', inputs: [{ name: 'Cedar Plank', qty: 10 }], outputs: [{ name: 'Cedar Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Fir Plank → Fir Plywood', inputs: [{ name: 'Fir Plank', qty: 10 }], outputs: [{ name: 'Fir Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Maple Plank → Maple Plywood', inputs: [{ name: 'Maple Plank', qty: 10 }], outputs: [{ name: 'Maple Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Pine Plank → Pine Plywood', inputs: [{ name: 'Pine Plank', qty: 10 }], outputs: [{ name: 'Pine Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'White Cedar Plank → White Cedar Plywood', inputs: [{ name: 'White Cedar Plank', qty: 10 }], outputs: [{ name: 'White Cedar Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Acacia Plank → Acacia Plywood', inputs: [{ name: 'Acacia Plank', qty: 10 }], outputs: [{ name: 'Acacia Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Palm Plank → Palm Plywood', inputs: [{ name: 'Palm Plank', qty: 10 }], outputs: [{ name: 'Palm Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Elder Tree Plank → Elder Tree Plywood', inputs: [{ name: 'Elder Tree Plank', qty: 10 }], outputs: [{ name: 'Elder Tree Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Thorn Tree Plank → Thorn Tree Plywood', inputs: [{ name: 'Thorn Tree Plank', qty: 10 }], outputs: [{ name: 'Thorn Tree Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Snowfield Cedar Plank → Snowfield Cedar Plywood', inputs: [{ name: 'Snowfield Cedar Plank', qty: 10 }], outputs: [{ name: 'Snowfield Cedar Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Moss Tree Plank → Moss Tree Plywood', inputs: [{ name: 'Moss Tree Plank', qty: 10 }], outputs: [{ name: 'Moss Tree Plywood', qty: 2 }] },
  { category: 'Chopping', name: 'Thornwood Plank → Thornwood Plywood', inputs: [{ name: 'Thornwood Plank', qty: 10 }], outputs: [{ name: 'Thornwood Plywood', qty: 2 }] },

  // CHOPPING — Misc
  { category: 'Chopping', name: 'Log → Usable Scantling', inputs: [{ name: 'Log', qty: 10 }], outputs: [{ name: 'Usable Scantling', qty: 2 }] },
  { category: 'Chopping', name: 'Usable Scantling → Standardized Timber Square', inputs: [{ name: 'Usable Scantling', qty: 10 }], outputs: [{ name: 'Standardized Timber Square', qty: 1 }] },

  // ═══════════════════════════════════════════════════════════════════════════════
  // GRINDING
  // ═══════════════════════════════════════════════════════════════════════════════
  // Grain → Flour
  { category: 'Grinding', name: 'Wheat → Wheat Flour', inputs: [{ name: 'Wheat', qty: 1 }], outputs: [{ name: 'Wheat Flour', qty: 2 }] },
  { category: 'Grinding', name: 'Barley → Barley Flour', inputs: [{ name: 'Barley', qty: 1 }], outputs: [{ name: 'Barley Flour', qty: 2 }] },
  { category: 'Grinding', name: 'Corn → Corn Flour', inputs: [{ name: 'Corn', qty: 1 }], outputs: [{ name: 'Corn Flour', qty: 2 }] },
  { category: 'Grinding', name: 'Potato → Potato Flour', inputs: [{ name: 'Potato', qty: 1 }], outputs: [{ name: 'Potato Flour', qty: 2 }] },
  { category: 'Grinding', name: 'Sweet Potato → Sweet Potato Flour', inputs: [{ name: 'Sweet Potato', qty: 1 }], outputs: [{ name: 'Sweet Potato Flour', qty: 2 }] },
  { category: 'Grinding', name: 'Teff → Teff Flour', inputs: [{ name: 'Teff', qty: 1 }], outputs: [{ name: 'Teff Flour', qty: 2 }] },
  { category: 'Grinding', name: 'Freekeh → Freekeh Flour', inputs: [{ name: 'Freekeh', qty: 1 }], outputs: [{ name: 'Freekeh Flour', qty: 2 }] },

  // Gem Grinding
  { category: 'Grinding', name: 'Rough Ruby → Ruby', inputs: [{ name: 'Rough Ruby', qty: 5 }], outputs: [{ name: 'Ruby', qty: 1 }] },
  { category: 'Grinding', name: 'Rough Sapphire → Sapphire', inputs: [{ name: 'Rough Sapphire', qty: 5 }], outputs: [{ name: 'Sapphire', qty: 1 }] },
  { category: 'Grinding', name: 'Rough Topaz → Topaz', inputs: [{ name: 'Rough Topaz', qty: 5 }], outputs: [{ name: 'Topaz', qty: 1 }] },
  { category: 'Grinding', name: 'Rough Emerald → Emerald', inputs: [{ name: 'Rough Emerald', qty: 5 }], outputs: [{ name: 'Emerald', qty: 1 }] },
  { category: 'Grinding', name: 'Rough Diamond → Diamond', inputs: [{ name: 'Rough Diamond', qty: 5 }], outputs: [{ name: 'Diamond', qty: 1 }] },

  // Fabric Grinding (yarn/thread → fabric)
  { category: 'Grinding', name: 'Cotton Yarn → Cotton Fabric', inputs: [{ name: 'Cotton Yarn', qty: 10 }], outputs: [{ name: 'Cotton Fabric', qty: 2 }] },
  { category: 'Grinding', name: 'Flax Thread → Flax Fabric', inputs: [{ name: 'Flax Thread', qty: 10 }], outputs: [{ name: 'Flax Fabric', qty: 2 }] },
  { category: 'Grinding', name: 'Silk Thread → Silk', inputs: [{ name: 'Silk Thread', qty: 10 }], outputs: [{ name: 'Silk', qty: 2 }] },
  { category: 'Grinding', name: 'Knitting Yarn → Wool', inputs: [{ name: 'Knitting Yarn', qty: 10 }], outputs: [{ name: 'Wool', qty: 2 }] },

  // Misc Grinding
  { category: 'Grinding', name: 'Rough Stone → Polished Stone', inputs: [{ name: 'Rough Stone', qty: 10 }], outputs: [{ name: 'Polished Stone', qty: 1 }] },
  { category: 'Grinding', name: 'Hard Black Crystal Shard → Black Stone (Armor)', inputs: [{ name: 'Hard Black Crystal Shard', qty: 2 }], outputs: [{ name: 'Black Stone (Armor)', qty: 3 }] },
  { category: 'Grinding', name: 'Sharp Black Crystal Shard → Black Stone (Weapon)', inputs: [{ name: 'Sharp Black Crystal Shard', qty: 2 }], outputs: [{ name: 'Black Stone (Weapon)', qty: 3 }] },

  // ═══════════════════════════════════════════════════════════════════════════════
  // DRYING — Fish (1 fish → 1-4 dried fish)
  // ═══════════════════════════════════════════════════════════════════════════════
  { category: 'Drying', name: 'Carp → Dried Carp', inputs: [{ name: 'Carp', qty: 1 }], outputs: [{ name: 'Dried Carp', qty: 2 }] },
  { category: 'Drying', name: 'Catfish → Dried Catfish', inputs: [{ name: 'Catfish', qty: 1 }], outputs: [{ name: 'Dried Catfish', qty: 2 }] },
  { category: 'Drying', name: 'Trout → Dried Trout', inputs: [{ name: 'Trout', qty: 1 }], outputs: [{ name: 'Dried Trout', qty: 2 }] },
  { category: 'Drying', name: 'Salmon → Dried Salmon', inputs: [{ name: 'Salmon', qty: 1 }], outputs: [{ name: 'Dried Salmon', qty: 2 }] },
  { category: 'Drying', name: 'Bass → Dried Bass', inputs: [{ name: 'Bass', qty: 1 }], outputs: [{ name: 'Dried Bass', qty: 2 }] },
  { category: 'Drying', name: 'Perch → Dried Perch', inputs: [{ name: 'Perch', qty: 1 }], outputs: [{ name: 'Dried Perch', qty: 2 }] },
  { category: 'Drying', name: 'Herring → Dried Herring', inputs: [{ name: 'Herring', qty: 1 }], outputs: [{ name: 'Dried Herring', qty: 2 }] },
  { category: 'Drying', name: 'Mackerel → Dried Mackerel', inputs: [{ name: 'Mackerel', qty: 1 }], outputs: [{ name: 'Dried Mackerel', qty: 2 }] },
  { category: 'Drying', name: 'Sardine → Dried Sardine', inputs: [{ name: 'Sardine', qty: 1 }], outputs: [{ name: 'Dried Sardine', qty: 2 }] },
  { category: 'Drying', name: 'Tuna → Dried Tuna', inputs: [{ name: 'Tuna', qty: 1 }], outputs: [{ name: 'Dried Tuna', qty: 2 }] },
  { category: 'Drying', name: 'Swordfish → Dried Swordfish', inputs: [{ name: 'Swordfish', qty: 1 }], outputs: [{ name: 'Dried Swordfish', qty: 2 }] },
  { category: 'Drying', name: 'Flounder → Dried Flounder', inputs: [{ name: 'Flounder', qty: 1 }], outputs: [{ name: 'Dried Flounder', qty: 2 }] },
  { category: 'Drying', name: 'Flatfish → Dried Flatfish', inputs: [{ name: 'Flatfish', qty: 1 }], outputs: [{ name: 'Dried Flatfish', qty: 2 }] },
  { category: 'Drying', name: 'Squid → Dried Squid', inputs: [{ name: 'Squid', qty: 1 }], outputs: [{ name: 'Dried Squid', qty: 2 }] },
  { category: 'Drying', name: 'Octopus → Dried Octopus', inputs: [{ name: 'Octopus', qty: 1 }], outputs: [{ name: 'Dried Octopus', qty: 2 }] },
  { category: 'Drying', name: 'Cuttlefish → Dried Cuttlefish', inputs: [{ name: 'Cuttlefish', qty: 1 }], outputs: [{ name: 'Dried Cuttlefish', qty: 2 }] },
  { category: 'Drying', name: 'Sea Bass → Dried Sea Bass', inputs: [{ name: 'Sea Bass', qty: 1 }], outputs: [{ name: 'Dried Sea Bass', qty: 2 }] },
  { category: 'Drying', name: 'Sea Eel → Dried Sea Eel', inputs: [{ name: 'Sea Eel', qty: 1 }], outputs: [{ name: 'Dried Sea Eel', qty: 2 }] },
  { category: 'Drying', name: 'Rockfish → Dried Rockfish', inputs: [{ name: 'Rockfish', qty: 1 }], outputs: [{ name: 'Dried Rockfish', qty: 2 }] },
  { category: 'Drying', name: 'Grouper → Dried Grouper', inputs: [{ name: 'Grouper', qty: 1 }], outputs: [{ name: 'Dried Grouper', qty: 2 }] },
  { category: 'Drying', name: 'Croaker → Dried Croaker', inputs: [{ name: 'Croaker', qty: 1 }], outputs: [{ name: 'Dried Croaker', qty: 2 }] },
  { category: 'Drying', name: 'Porgy → Dried Porgy', inputs: [{ name: 'Porgy', qty: 1 }], outputs: [{ name: 'Dried Porgy', qty: 2 }] },
  { category: 'Drying', name: 'Grunt → Dried Grunt', inputs: [{ name: 'Grunt', qty: 1 }], outputs: [{ name: 'Dried Grunt', qty: 2 }] },
  { category: 'Drying', name: 'Bluefish → Dried Bluefish', inputs: [{ name: 'Bluefish', qty: 1 }], outputs: [{ name: 'Dried Bluefish', qty: 2 }] },
  { category: 'Drying', name: 'Pomfret → Dried Pomfret', inputs: [{ name: 'Pomfret', qty: 1 }], outputs: [{ name: 'Dried Pomfret', qty: 2 }] },
  { category: 'Drying', name: 'Snakehead → Dried Snakehead', inputs: [{ name: 'Snakehead', qty: 1 }], outputs: [{ name: 'Dried Snakehead', qty: 2 }] },
  { category: 'Drying', name: 'Smelt → Dried Smelt', inputs: [{ name: 'Smelt', qty: 1 }], outputs: [{ name: 'Dried Smelt', qty: 2 }] },
  { category: 'Drying', name: 'Beltfish → Dried Beltfish', inputs: [{ name: 'Beltfish', qty: 1 }], outputs: [{ name: 'Dried Beltfish', qty: 2 }] },
  { category: 'Drying', name: 'Filefish → Dried Filefish', inputs: [{ name: 'Filefish', qty: 1 }], outputs: [{ name: 'Dried Filefish', qty: 2 }] },
  { category: 'Drying', name: 'Mullet → Dried Mullet', inputs: [{ name: 'Mullet', qty: 1 }], outputs: [{ name: 'Dried Mullet', qty: 2 }] },
  { category: 'Drying', name: 'Ray → Dried Ray', inputs: [{ name: 'Ray', qty: 1 }], outputs: [{ name: 'Dried Ray', qty: 2 }] },
  { category: 'Drying', name: 'Crab → Dried Crab', inputs: [{ name: 'Crab', qty: 1 }], outputs: [{ name: 'Dried Crab', qty: 2 }] },
  { category: 'Drying', name: 'Jellyfish → Dried Jellyfish', inputs: [{ name: 'Jellyfish', qty: 1 }], outputs: [{ name: 'Dried Jellyfish', qty: 2 }] },
  { category: 'Drying', name: 'Starfish → Dried Starfish', inputs: [{ name: 'Starfish', qty: 1 }], outputs: [{ name: 'Dried Starfish', qty: 2 }] },
  { category: 'Drying', name: 'Seahorse → Dried Seahorse', inputs: [{ name: 'Seahorse', qty: 1 }], outputs: [{ name: 'Dried Seahorse', qty: 2 }] },
  { category: 'Drying', name: 'Shellfish → Dried Shellfish', inputs: [{ name: 'Shellfish', qty: 1 }], outputs: [{ name: 'Dried Shellfish', qty: 2 }] },
  { category: 'Drying', name: 'Clownfish → Dried Clownfish', inputs: [{ name: 'Clownfish', qty: 1 }], outputs: [{ name: 'Dried Clownfish', qty: 2 }] },
  { category: 'Drying', name: 'Blue Tang → Dried Blue Tang', inputs: [{ name: 'Blue Tang', qty: 1 }], outputs: [{ name: 'Dried Blue Tang', qty: 2 }] },
  { category: 'Drying', name: 'Angler → Dried Angler', inputs: [{ name: 'Angler', qty: 1 }], outputs: [{ name: 'Dried Angler', qty: 2 }] },
  { category: 'Drying', name: 'Skipjack → Dried Skipjack', inputs: [{ name: 'Skipjack', qty: 1 }], outputs: [{ name: 'Dried Skipjack', qty: 2 }] },
  { category: 'Drying', name: 'Sunfish → Dried Sunfish', inputs: [{ name: 'Sunfish', qty: 1 }], outputs: [{ name: 'Dried Sunfish', qty: 2 }] },
  { category: 'Drying', name: 'Flying Fish → Dried Flying Fish', inputs: [{ name: 'Flying Fish', qty: 1 }], outputs: [{ name: 'Dried Flying Fish', qty: 2 }] },
  { category: 'Drying', name: 'Gurnard → Dried Gurnard', inputs: [{ name: 'Gurnard', qty: 1 }], outputs: [{ name: 'Dried Gurnard', qty: 2 }] },
  { category: 'Drying', name: 'Dolphinfish → Dried Dolphinfish', inputs: [{ name: 'Dolphinfish', qty: 1 }], outputs: [{ name: 'Dried Dolphinfish', qty: 2 }] },
  { category: 'Drying', name: 'John Dory → Dried John Dory', inputs: [{ name: 'John Dory', qty: 1 }], outputs: [{ name: 'Dried John Dory', qty: 2 }] },
  { category: 'Drying', name: 'Greenling → Dried Greenling', inputs: [{ name: 'Greenling', qty: 1 }], outputs: [{ name: 'Dried Greenling', qty: 2 }] },
  { category: 'Drying', name: 'Tilefish → Dried Tilefish', inputs: [{ name: 'Tilefish', qty: 1 }], outputs: [{ name: 'Dried Tilefish', qty: 2 }] },
  { category: 'Drying', name: 'Saurel → Dried Saurel', inputs: [{ name: 'Saurel', qty: 1 }], outputs: [{ name: 'Dried Saurel', qty: 2 }] },
  { category: 'Drying', name: 'Amberjack → Dried Amberjack', inputs: [{ name: 'Amberjack', qty: 1 }], outputs: [{ name: 'Dried Amberjack', qty: 2 }] },
  { category: 'Drying', name: 'Sturgeon → Dried Sturgeon', inputs: [{ name: 'Sturgeon', qty: 1 }], outputs: [{ name: 'Dried Sturgeon', qty: 2 }] },
  { category: 'Drying', name: 'Freshwater Eel → Dried Freshwater Eel', inputs: [{ name: 'Freshwater Eel', qty: 1 }], outputs: [{ name: 'Dried Freshwater Eel', qty: 2 }] },
  { category: 'Drying', name: 'Arowana → Dried Arowana', inputs: [{ name: 'Arowana', qty: 1 }], outputs: [{ name: 'Dried Arowana', qty: 2 }] },
  { category: 'Drying', name: 'Lenok → Dried Lenok', inputs: [{ name: 'Lenok', qty: 1 }], outputs: [{ name: 'Dried Lenok', qty: 2 }] },
  { category: 'Drying', name: 'Sweetfish → Dried Sweetfish', inputs: [{ name: 'Sweetfish', qty: 1 }], outputs: [{ name: 'Dried Sweetfish', qty: 2 }] },
  { category: 'Drying', name: 'Crawfish → Dried Crawfish', inputs: [{ name: 'Crawfish', qty: 1 }], outputs: [{ name: 'Dried Crawfish', qty: 2 }] },
  { category: 'Drying', name: 'Mudfish → Dried Mudfish', inputs: [{ name: 'Mudfish', qty: 1 }], outputs: [{ name: 'Dried Mudfish', qty: 2 }] },
  { category: 'Drying', name: 'Crucian Carp → Dried Crucian Carp', inputs: [{ name: 'Crucian Carp', qty: 1 }], outputs: [{ name: 'Dried Crucian Carp', qty: 2 }] },
  { category: 'Drying', name: 'Cherry Salmon → Dried Cherry Salmon', inputs: [{ name: 'Cherry Salmon', qty: 1 }], outputs: [{ name: 'Dried Cherry Salmon', qty: 2 }] },
  { category: 'Drying', name: 'Piranha → Dried Piranha', inputs: [{ name: 'Piranha', qty: 1 }], outputs: [{ name: 'Dried Piranha', qty: 2 }] },
  { category: 'Drying', name: 'Pacu → Dried Pacu', inputs: [{ name: 'Pacu', qty: 1 }], outputs: [{ name: 'Dried Pacu', qty: 2 }] },
  { category: 'Drying', name: 'Pintado → Dried Pintado', inputs: [{ name: 'Pintado', qty: 1 }], outputs: [{ name: 'Dried Pintado', qty: 2 }] },
  { category: 'Drying', name: 'Swellfish → Dried Swellfish', inputs: [{ name: 'Swellfish', qty: 1 }], outputs: [{ name: 'Dried Swellfish', qty: 2 }] },
  { category: 'Drying', name: 'Moray → Dried Moray', inputs: [{ name: 'Moray', qty: 1 }], outputs: [{ name: 'Dried Moray', qty: 2 }] },
  { category: 'Drying', name: 'Round Herring → Dried Round Herring', inputs: [{ name: 'Round Herring', qty: 1 }], outputs: [{ name: 'Dried Round Herring', qty: 2 }] },
  { category: 'Drying', name: 'Silver Stripe Round Herring → Dried Silver Stripe Round Herring', inputs: [{ name: 'Silver Stripe Round Herring', qty: 1 }], outputs: [{ name: 'Dried Silver Stripe Round Herring', qty: 2 }] },
  { category: 'Drying', name: 'Abalone → Dried Abalone', inputs: [{ name: 'Abalone', qty: 1 }], outputs: [{ name: 'Dried Abalone', qty: 2 }] },
  { category: 'Drying', name: 'Atka Mackerel → Dried Atka Mackerel', inputs: [{ name: 'Atka Mackerel', qty: 1 }], outputs: [{ name: 'Dried Atka Mackerel', qty: 2 }] },
  { category: 'Drying', name: 'Bitterling → Dried Bitterling', inputs: [{ name: 'Bitterling', qty: 1 }], outputs: [{ name: 'Dried Bitterling', qty: 2 }] },
  { category: 'Drying', name: 'Blackfin Sweeper → Dried Blackfin Sweeper', inputs: [{ name: 'Blackfin Sweeper', qty: 1 }], outputs: [{ name: 'Dried Blackfin Sweeper', qty: 2 }] },
  { category: 'Drying', name: 'Bleeker → Dried Bleeker', inputs: [{ name: 'Bleeker', qty: 1 }], outputs: [{ name: 'Dried Bleeker', qty: 2 }] },
  { category: 'Drying', name: 'Bubble Eye → Dried Bubble Eye', inputs: [{ name: 'Bubble Eye', qty: 1 }], outputs: [{ name: 'Dried Bubble Eye', qty: 2 }] },
  { category: 'Drying', name: 'Butterflyfish → Dried Butterflyfish', inputs: [{ name: 'Butterflyfish', qty: 1 }], outputs: [{ name: 'Dried Butterflyfish', qty: 2 }] },
  { category: 'Drying', name: 'Checkerboard Wrasse → Dried Checkerboard Wrasse', inputs: [{ name: 'Checkerboard Wrasse', qty: 1 }], outputs: [{ name: 'Dried Checkerboard Wrasse', qty: 2 }] },
  { category: 'Drying', name: 'Cornet Fish → Dried Cornet Fish', inputs: [{ name: 'Cornet Fish', qty: 1 }], outputs: [{ name: 'Dried Cornet Fish', qty: 2 }] },
  { category: 'Drying', name: 'Cuvier → Dried Cuvier', inputs: [{ name: 'Cuvier', qty: 1 }], outputs: [{ name: 'Dried Cuvier', qty: 2 }] },
  { category: 'Drying', name: 'Dace → Dried Dace', inputs: [{ name: 'Dace', qty: 1 }], outputs: [{ name: 'Dried Dace', qty: 2 }] },
  { category: 'Drying', name: 'Diamond Minnow → Dried Diamond Minnow', inputs: [{ name: 'Diamond Minnow', qty: 1 }], outputs: [{ name: 'Dried Diamond Minnow', qty: 2 }] },
  { category: 'Drying', name: 'Diamond Starfish → Dried Diamond Starfish', inputs: [{ name: 'Diamond Starfish', qty: 1 }], outputs: [{ name: 'Dried Diamond Starfish', qty: 2 }] },
  { category: 'Drying', name: 'Dollarfish → Dried Dollarfish', inputs: [{ name: 'Dollarfish', qty: 1 }], outputs: [{ name: 'Dried Dollarfish', qty: 2 }] },
  { category: 'Drying', name: 'Fourfinger Threadfin → Dried Fourfinger Threadfin', inputs: [{ name: 'Fourfinger Threadfin', qty: 1 }], outputs: [{ name: 'Dried Fourfinger Threadfin', qty: 2 }] },
  { category: 'Drying', name: 'Goby Minnow → Dried Goby Minnow', inputs: [{ name: 'Goby Minnow', qty: 1 }], outputs: [{ name: 'Dried Goby Minnow', qty: 2 }] },
  { category: 'Drying', name: 'Golden-Thread → Dried Golden-Thread', inputs: [{ name: 'Golden-Thread', qty: 1 }], outputs: [{ name: 'Dried Golden-Thread', qty: 2 }] },
  { category: 'Drying', name: 'Grayling → Dried Grayling', inputs: [{ name: 'Grayling', qty: 1 }], outputs: [{ name: 'Dried Grayling', qty: 2 }] },
  { category: 'Drying', name: 'Gunnel → Dried Gunnel', inputs: [{ name: 'Gunnel', qty: 1 }], outputs: [{ name: 'Dried Gunnel', qty: 2 }] },
  { category: 'Drying', name: 'Horn Fish → Dried Horn Fish', inputs: [{ name: 'Horn Fish', qty: 1 }], outputs: [{ name: 'Dried Horn Fish', qty: 2 }] },
  { category: 'Drying', name: 'Kuhlia Marginata → Dried Kuhlia Marginata', inputs: [{ name: 'Kuhlia Marginata', qty: 1 }], outputs: [{ name: 'Dried Kuhlia Marginata', qty: 2 }] },
  { category: 'Drying', name: 'Leather Carp → Dried Leather Carp', inputs: [{ name: 'Leather Carp', qty: 1 }], outputs: [{ name: 'Dried Leather Carp', qty: 2 }] },
  { category: 'Drying', name: 'Mackerel Pike → Dried Mackerel Pike', inputs: [{ name: 'Mackerel Pike', qty: 1 }], outputs: [{ name: 'Dried Mackerel Pike', qty: 2 }] },
  { category: 'Drying', name: 'Mandarin Fish → Dried Mandarin Fish', inputs: [{ name: 'Mandarin Fish', qty: 1 }], outputs: [{ name: 'Dried Mandarin Fish', qty: 2 }] },
  { category: 'Drying', name: 'Maomao → Dried Maomao', inputs: [{ name: 'Maomao', qty: 1 }], outputs: [{ name: 'Dried Maomao', qty: 2 }] },
  { category: 'Drying', name: 'Miho Spine Loach → Dried Miho Spine Loach', inputs: [{ name: 'Miho Spine Loach', qty: 1 }], outputs: [{ name: 'Dried Miho Spine Loach', qty: 2 }] },
  { category: 'Drying', name: 'Mudskipper → Dried Mudskipper', inputs: [{ name: 'Mudskipper', qty: 1 }], outputs: [{ name: 'Dried Mudskipper', qty: 2 }] },
  { category: 'Drying', name: 'Nibbler → Dried Nibbler', inputs: [{ name: 'Nibbler', qty: 1 }], outputs: [{ name: 'Dried Nibbler', qty: 2 }] },
  { category: 'Drying', name: 'Notch Jaw → Dried Notch Jaw', inputs: [{ name: 'Notch Jaw', qty: 1 }], outputs: [{ name: 'Dried Notch Jaw', qty: 2 }] },
  { category: 'Drying', name: 'Porcupine Fish → Dried Porcupine Fish', inputs: [{ name: 'Porcupine Fish', qty: 1 }], outputs: [{ name: 'Dried Porcupine Fish', qty: 2 }] },
  { category: 'Drying', name: 'Rock Hind → Dried Rock Hind', inputs: [{ name: 'Rock Hind', qty: 1 }], outputs: [{ name: 'Dried Rock Hind', qty: 2 }] },
  { category: 'Drying', name: 'Rosefish → Dried Rosefish', inputs: [{ name: 'Rosefish', qty: 1 }], outputs: [{ name: 'Dried Rosefish', qty: 2 }] },
  { category: 'Drying', name: 'Rosy Bitterling → Dried Rosy Bitterling', inputs: [{ name: 'Rosy Bitterling', qty: 1 }], outputs: [{ name: 'Dried Rosy Bitterling', qty: 2 }] },
  { category: 'Drying', name: 'Roundtail Paradisefish → Dried Roundtail Paradisefish', inputs: [{ name: 'Roundtail Paradisefish', qty: 1 }], outputs: [{ name: 'Dried Roundtail Paradisefish', qty: 2 }] },
  { category: 'Drying', name: 'Sandeel → Dried Sandeel', inputs: [{ name: 'Sandeel', qty: 1 }], outputs: [{ name: 'Dried Sandeel', qty: 2 }] },
  { category: 'Drying', name: 'Sandfish → Dried Sandfish', inputs: [{ name: 'Sandfish', qty: 1 }], outputs: [{ name: 'Dried Sandfish', qty: 2 }] },
  { category: 'Drying', name: 'Scorpion Fish → Dried Scorpion Fish', inputs: [{ name: 'Scorpion Fish', qty: 1 }], outputs: [{ name: 'Dried Scorpion Fish', qty: 2 }] },
  { category: 'Drying', name: 'Siganid → Dried Siganid', inputs: [{ name: 'Siganid', qty: 1 }], outputs: [{ name: 'Dried Siganid', qty: 2 }] },
  { category: 'Drying', name: 'Smokey Chromis → Dried Smokey Chromis', inputs: [{ name: 'Smokey Chromis', qty: 1 }], outputs: [{ name: 'Dried Smokey Chromis', qty: 2 }] },
  { category: 'Drying', name: 'Soho Bitterling → Dried Soho Bitterling', inputs: [{ name: 'Soho Bitterling', qty: 1 }], outputs: [{ name: 'Dried Soho Bitterling', qty: 2 }] },
  { category: 'Drying', name: 'Striped Catfish → Dried Striped Catfish', inputs: [{ name: 'Striped Catfish', qty: 1 }], outputs: [{ name: 'Dried Striped Catfish', qty: 2 }] },
  { category: 'Drying', name: 'Striped Shiner → Dried Striped Shiner', inputs: [{ name: 'Striped Shiner', qty: 1 }], outputs: [{ name: 'Dried Striped Shiner', qty: 2 }] },
  { category: 'Drying', name: 'Surfperch → Dried Surfperch', inputs: [{ name: 'Surfperch', qty: 1 }], outputs: [{ name: 'Dried Surfperch', qty: 2 }] },
  { category: 'Drying', name: 'Swiri → Dried Swiri', inputs: [{ name: 'Swiri', qty: 1 }], outputs: [{ name: 'Dried Swiri', qty: 2 }] },
  { category: 'Drying', name: 'Tapertail Anchovy → Dried Tapertail Anchovy', inputs: [{ name: 'Tapertail Anchovy', qty: 1 }], outputs: [{ name: 'Dried Tapertail Anchovy', qty: 2 }] },
  { category: 'Drying', name: 'Tongue Sole → Dried Tongue Sole', inputs: [{ name: 'Tongue Sole', qty: 1 }], outputs: [{ name: 'Dried Tongue Sole', qty: 2 }] },
  { category: 'Drying', name: 'Whiting → Dried Whiting', inputs: [{ name: 'Whiting', qty: 1 }], outputs: [{ name: 'Dried Whiting', qty: 2 }] },
  { category: 'Drying', name: 'Yellow Fin Sculpin → Dried Yellow Fin Sculpin', inputs: [{ name: 'Yellow Fin Sculpin', qty: 1 }], outputs: [{ name: 'Dried Yellow Fin Sculpin', qty: 2 }] },
  { category: 'Drying', name: 'Yellow-Head Catfish → Dried Yellow-Head Catfish', inputs: [{ name: 'Yellow-Head Catfish', qty: 1 }], outputs: [{ name: 'Dried Yellow-Head Catfish', qty: 2 }] },
  { category: 'Drying', name: 'Shrimp → Dried Shrimp', inputs: [{ name: 'Shrimp', qty: 1 }], outputs: [{ name: 'Dried Shrimp', qty: 2 }] },
  { category: 'Drying', name: 'Spotted Barbel → Dried Spotted Barbel', inputs: [{ name: 'Spotted Barbel', qty: 1 }], outputs: [{ name: 'Dried Spotted Barbel', qty: 2 }] },
  { category: 'Drying', name: 'Snapper → Dried Snapper', inputs: [{ name: 'Snapper', qty: 1 }], outputs: [{ name: 'Dried Snapper', qty: 2 }] },
  { category: 'Drying', name: 'Bigeye → Dried Bigeye', inputs: [{ name: 'Bigeye', qty: 1 }], outputs: [{ name: 'Dried Bigeye', qty: 2 }] },
  { category: 'Drying', name: 'Eyespot Puffer → Dried Eyespot Puffer', inputs: [{ name: 'Eyespot Puffer', qty: 1 }], outputs: [{ name: 'Dried Eyespot Puffer', qty: 2 }] },
  { category: 'Drying', name: 'Gizzard Shad → Dried Gizzard Shad', inputs: [{ name: 'Gizzard Shad', qty: 1 }], outputs: [{ name: 'Dried Gizzard Shad', qty: 2 }] },
  { category: 'Drying', name: 'Golden Siniperca → Dried Golden Siniperca', inputs: [{ name: 'Golden Siniperca', qty: 1 }], outputs: [{ name: 'Dried Golden Siniperca', qty: 2 }] },
  { category: 'Drying', name: 'Grunt Fish → Dried Grunt Fish', inputs: [{ name: 'Grunt Fish', qty: 1 }], outputs: [{ name: 'Dried Grunt Fish', qty: 2 }] },
  { category: 'Drying', name: 'Hare → Dried Hare', inputs: [{ name: 'Hare', qty: 1 }], outputs: [{ name: 'Dried Hare', qty: 2 }] },
  { category: 'Drying', name: 'King Archelon → Dried King Archelon', inputs: [{ name: 'King Archelon', qty: 1 }], outputs: [{ name: 'Dried King Archelon', qty: 2 }] },
  { category: 'Drying', name: 'Marlin → Dried Marlin', inputs: [{ name: 'Marlin', qty: 1 }], outputs: [{ name: 'Dried Marlin', qty: 2 }] },
  { category: 'Drying', name: 'Minnow → Dried Minnow', inputs: [{ name: 'Minnow', qty: 1 }], outputs: [{ name: 'Dried Minnow', qty: 2 }] },
  { category: 'Drying', name: 'Monk Fish → Dried Monk Fish', inputs: [{ name: 'Monk Fish', qty: 1 }], outputs: [{ name: 'Dried Monk Fish', qty: 2 }] },
  { category: 'Drying', name: 'Pirarucu → Dried Pirarucu', inputs: [{ name: 'Pirarucu', qty: 1 }], outputs: [{ name: 'Dried Pirarucu', qty: 2 }] },
  { category: 'Drying', name: 'Sea Perch → Dried Sea Perch', inputs: [{ name: 'Sea Perch', qty: 1 }], outputs: [{ name: 'Dried Sea Perch', qty: 2 }] },
  { category: 'Drying', name: 'Sea Trumpet → Dried Sea Trumpet', inputs: [{ name: 'Sea Trumpet', qty: 1 }], outputs: [{ name: 'Dried Sea Trumpet', qty: 2 }] },
  { category: 'Drying', name: 'Stickleback → Dried Stickleback', inputs: [{ name: 'Stickleback', qty: 1 }], outputs: [{ name: 'Dried Stickleback', qty: 2 }] },
  { category: 'Drying', name: 'Terrapin → Dried Terrapin', inputs: [{ name: 'Terrapin', qty: 1 }], outputs: [{ name: 'Dried Terrapin', qty: 2 }] },
  { category: 'Drying', name: 'Whale Shark → Dried Whale Shark', inputs: [{ name: 'Whale Shark', qty: 1 }], outputs: [{ name: 'Dried Whale Shark', qty: 2 }] },
  { category: 'Drying', name: 'Yellowfin Tuna → Dried Yellowfin Tuna', inputs: [{ name: 'Yellowfin Tuna', qty: 1 }], outputs: [{ name: 'Dried Yellowfin Tuna', qty: 2 }] },
  { category: 'Drying', name: 'Gourami → Dried Gourami', inputs: [{ name: 'Gourami', qty: 1 }], outputs: [{ name: 'Dried Gourami', qty: 2 }] },
  { category: 'Drying', name: 'Giant Octopus → Dried Giant Octopus', inputs: [{ name: 'Giant Octopus', qty: 1 }], outputs: [{ name: 'Dried Giant Octopus', qty: 2 }] },
  { category: 'Drying', name: 'Sea Horse → Dried Sea Horse', inputs: [{ name: 'Sea Horse', qty: 1 }], outputs: [{ name: 'Dried Sea Horse', qty: 2 }] },
  { category: 'Drying', name: 'Eel → Dried Eel', inputs: [{ name: 'Eel', qty: 1 }], outputs: [{ name: 'Dried Eel', qty: 2 }] },
  { category: 'Drying', name: 'Pike → Dried Pike', inputs: [{ name: 'Pike', qty: 1 }], outputs: [{ name: 'Dried Pike', qty: 2 }] },
  { category: 'Drying', name: 'Combfish → Dried Combfish', inputs: [{ name: 'Combfish', qty: 1 }], outputs: [{ name: 'Dried Combfish', qty: 2 }] },
  { category: 'Drying', name: 'Winding Fish → Dried Winding Fish', inputs: [{ name: 'Winding Fish', qty: 1 }], outputs: [{ name: 'Dried Winding Fish', qty: 2 }] },
  { category: 'Drying', name: 'Luvar → Dried Luvar', inputs: [{ name: 'Luvar', qty: 1 }], outputs: [{ name: 'Dried Luvar', qty: 2 }] },
  { category: 'Drying', name: 'Tanbager → Dried Tanbager', inputs: [{ name: 'Tanbager', qty: 1 }], outputs: [{ name: 'Dried Tanbager', qty: 2 }] },

  // DRYING — Hides
  { category: 'Drying', name: 'Deer Hide → Soft Hide', inputs: [{ name: 'Deer Hide', qty: 5 }], outputs: [{ name: 'Soft Hide', qty: 2 }] },
  { category: 'Drying', name: 'Sheep Hide → Soft Hide', inputs: [{ name: 'Sheep Hide', qty: 5 }], outputs: [{ name: 'Soft Hide', qty: 2 }] },
  { category: 'Drying', name: 'Fox Hide → Soft Hide', inputs: [{ name: 'Fox Hide', qty: 5 }], outputs: [{ name: 'Soft Hide', qty: 2 }] },
  { category: 'Drying', name: 'Rhino Hide → Tough Hide', inputs: [{ name: 'Rhino Hide', qty: 5 }], outputs: [{ name: 'Tough Hide', qty: 2 }] },
  { category: 'Drying', name: 'Pig Hide → Tough Hide', inputs: [{ name: 'Pig Hide', qty: 5 }], outputs: [{ name: 'Tough Hide', qty: 2 }] },
  { category: 'Drying', name: 'Ox Hide → Tough Hide', inputs: [{ name: 'Ox Hide', qty: 5 }], outputs: [{ name: 'Tough Hide', qty: 2 }] },
  { category: 'Drying', name: 'Bear Hide → Thick Fur', inputs: [{ name: 'Bear Hide', qty: 5 }], outputs: [{ name: 'Thick Fur', qty: 2 }] },
  { category: 'Drying', name: 'Wolf Hide → Thick Fur', inputs: [{ name: 'Wolf Hide', qty: 5 }], outputs: [{ name: 'Thick Fur', qty: 2 }] },
  { category: 'Drying', name: 'Lion Hide → Thick Fur', inputs: [{ name: 'Lion Hide', qty: 5 }], outputs: [{ name: 'Thick Fur', qty: 2 }] },
  { category: 'Drying', name: 'Lizard Hide → Hard Hide', inputs: [{ name: 'Lizard Hide', qty: 5 }], outputs: [{ name: 'Hard Hide', qty: 2 }] },
  { category: 'Drying', name: 'Worm Hide → Hard Hide', inputs: [{ name: 'Worm Hide', qty: 5 }], outputs: [{ name: 'Hard Hide', qty: 2 }] },
  { category: 'Drying', name: 'Weasel Hide → Thin Hide', inputs: [{ name: 'Weasel Hide', qty: 5 }], outputs: [{ name: 'Thin Hide', qty: 2 }] },
  { category: 'Drying', name: 'Raccoon Hide → Thin Hide', inputs: [{ name: 'Raccoon Hide', qty: 5 }], outputs: [{ name: 'Thin Hide', qty: 2 }] },
  { category: 'Drying', name: 'Waragon Hide → Fancy Fur', inputs: [{ name: 'Waragon Hide', qty: 5 }], outputs: [{ name: 'Fancy Fur', qty: 2 }] },
  { category: 'Drying', name: 'Cheetah Dragon Hide → Fancy Fur', inputs: [{ name: 'Cheetah Dragon Hide', qty: 5 }], outputs: [{ name: 'Fancy Fur', qty: 2 }] },

  // DRYING — Fine Hides (10 base → fine)
  { category: 'Drying', name: 'Soft Hide → Fine Soft Hide', inputs: [{ name: 'Soft Hide', qty: 10 }], outputs: [{ name: 'Fine Soft Hide', qty: 1 }] },
  { category: 'Drying', name: 'Tough Hide → Fine Tough Hide', inputs: [{ name: 'Tough Hide', qty: 10 }], outputs: [{ name: 'Fine Tough Hide', qty: 1 }] },
  { category: 'Drying', name: 'Thick Fur → Fine Thick Fur', inputs: [{ name: 'Thick Fur', qty: 10 }], outputs: [{ name: 'Fine Thick Fur', qty: 1 }] },
  { category: 'Drying', name: 'Hard Hide → Fine Hard Hide', inputs: [{ name: 'Hard Hide', qty: 10 }], outputs: [{ name: 'Fine Hard Hide', qty: 1 }] },
  { category: 'Drying', name: 'Thin Hide → Fine Thin Hide', inputs: [{ name: 'Thin Hide', qty: 10 }], outputs: [{ name: 'Fine Thin Hide', qty: 1 }] },
  { category: 'Drying', name: 'Fancy Fur → Fine Fancy Fur', inputs: [{ name: 'Fancy Fur', qty: 10 }], outputs: [{ name: 'Fine Fancy Fur', qty: 1 }] },

  // DRYING — Meat
  { category: 'Drying', name: 'Deer Meat → Rare Jerky', inputs: [{ name: 'Deer Meat', qty: 1 }], outputs: [{ name: 'Rare Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Pork → Rare Jerky', inputs: [{ name: 'Pork', qty: 1 }], outputs: [{ name: 'Rare Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Beef → Rare Jerky', inputs: [{ name: 'Beef', qty: 1 }], outputs: [{ name: 'Rare Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Fox Meat → Fragrant Jerky', inputs: [{ name: 'Fox Meat', qty: 1 }], outputs: [{ name: 'Fragrant Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Bear Meat → Fragrant Jerky', inputs: [{ name: 'Bear Meat', qty: 1 }], outputs: [{ name: 'Fragrant Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Wolf Meat → Fragrant Jerky', inputs: [{ name: 'Wolf Meat', qty: 1 }], outputs: [{ name: 'Fragrant Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Weasel Meat → Fragrant Jerky', inputs: [{ name: 'Weasel Meat', qty: 1 }], outputs: [{ name: 'Fragrant Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Lamb Meat → Well-Dried Jerky', inputs: [{ name: 'Lamb Meat', qty: 1 }], outputs: [{ name: 'Well-Dried Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Lizard Meat → Well-Dried Jerky', inputs: [{ name: 'Lizard Meat', qty: 1 }], outputs: [{ name: 'Well-Dried Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Kuku Bird Meat → Well-Dried Jerky', inputs: [{ name: 'Kuku Bird Meat', qty: 1 }], outputs: [{ name: 'Well-Dried Jerky', qty: 2 }] },
  { category: 'Drying', name: 'Flamingo Meat → Well-Dried Jerky', inputs: [{ name: 'Flamingo Meat', qty: 1 }], outputs: [{ name: 'Well-Dried Jerky', qty: 2 }] },

  // DRYING — Cheese
  { category: 'Drying', name: 'Milk → Cheese', inputs: [{ name: 'Milk', qty: 1 }], outputs: [{ name: 'Cheese', qty: 2 }] },

  // DRYING — Crops → Fertilizer
  { category: 'Drying', name: 'Wheat → Inorganic Fertilizer', inputs: [{ name: 'Wheat', qty: 5 }], outputs: [{ name: 'Inorganic Fertilizer', qty: 1 }] },
  { category: 'Drying', name: 'Barley → Inorganic Fertilizer', inputs: [{ name: 'Barley', qty: 5 }], outputs: [{ name: 'Inorganic Fertilizer', qty: 1 }] },
  { category: 'Drying', name: 'Potato → Inorganic Fertilizer', inputs: [{ name: 'Potato', qty: 5 }], outputs: [{ name: 'Inorganic Fertilizer', qty: 1 }] },
  { category: 'Drying', name: 'Sweet Potato → Inorganic Fertilizer', inputs: [{ name: 'Sweet Potato', qty: 5 }], outputs: [{ name: 'Inorganic Fertilizer', qty: 1 }] },
  { category: 'Drying', name: 'Corn → Inorganic Fertilizer', inputs: [{ name: 'Corn', qty: 5 }], outputs: [{ name: 'Inorganic Fertilizer', qty: 1 }] },

  // ═══════════════════════════════════════════════════════════════════════════════
  // FILTERING
  // ═══════════════════════════════════════════════════════════════════════════════
  { category: 'Filtering', name: 'Cotton → Cotton Fabric', inputs: [{ name: 'Cotton', qty: 5 }], outputs: [{ name: 'Cotton Fabric', qty: 1 }] },
  { category: 'Filtering', name: 'Flax → Flax Fabric', inputs: [{ name: 'Flax', qty: 5 }], outputs: [{ name: 'Flax Fabric', qty: 1 }] },
  { category: 'Filtering', name: 'Wool → Wool Fabric', inputs: [{ name: 'Wool', qty: 5 }], outputs: [{ name: 'Wool Fabric', qty: 1 }] },
  { category: 'Filtering', name: 'Silk → Silk Thread', inputs: [{ name: 'Silk', qty: 5 }], outputs: [{ name: 'Silk Thread', qty: 1 }] },
  { category: 'Filtering', name: 'Fleece → Wool', inputs: [{ name: 'Fleece', qty: 5 }], outputs: [{ name: 'Wool', qty: 1 }] },
  { category: 'Filtering', name: 'River Water → Purified Water', inputs: [{ name: 'Bottle of River Water', qty: 1 }], outputs: [{ name: 'Purified Water', qty: 2 }] },
  { category: 'Filtering', name: 'Muddy Water → Purified Water', inputs: [{ name: 'Bag of Muddy Water', qty: 5 }], outputs: [{ name: 'Purified Water', qty: 2 }] },
  { category: 'Filtering', name: 'Cactus Sap → Purified Water', inputs: [{ name: 'Cactus Sap', qty: 5 }], outputs: [{ name: 'Purified Water', qty: 2 }] },
  { category: 'Filtering', name: 'Lightweight Plume → Fine Lightweight Plume', inputs: [{ name: 'Lightweight Plume', qty: 10 }], outputs: [{ name: 'Fine Lightweight Plume', qty: 1 }] },
  { category: 'Filtering', name: 'Fancy Feather → Fine Fancy Feather', inputs: [{ name: 'Fancy Feather', qty: 10 }], outputs: [{ name: 'Fine Fancy Feather', qty: 1 }] },

  // ═══════════════════════════════════════════════════════════════════════════════
  // SHAKING
  // ═══════════════════════════════════════════════════════════════════════════════
  // Dough
  { category: 'Shaking', name: 'Wheat Flour + Water → Wheat Dough', inputs: [{ name: 'Wheat Flour', qty: 1 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Wheat Dough', qty: 2 }] },
  { category: 'Shaking', name: 'Barley Flour + Water → Barley Dough', inputs: [{ name: 'Barley Flour', qty: 1 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Barley Dough', qty: 2 }] },
  { category: 'Shaking', name: 'Corn Flour + Water → Corn Dough', inputs: [{ name: 'Corn Flour', qty: 1 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Corn Dough', qty: 2 }] },
  { category: 'Shaking', name: 'Potato Flour + Water → Potato Dough', inputs: [{ name: 'Potato Flour', qty: 1 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Potato Dough', qty: 2 }] },
  { category: 'Shaking', name: 'Sweet Potato Flour + Water → Sweet Potato Dough', inputs: [{ name: 'Sweet Potato Flour', qty: 1 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Sweet Potato Dough', qty: 2 }] },
  { category: 'Shaking', name: 'Teff Flour + Water → Teff Dough', inputs: [{ name: 'Teff Flour', qty: 1 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Teff Flour Dough', qty: 2 }] },
  { category: 'Shaking', name: 'Freekeh Flour + Water → Freekeh Dough', inputs: [{ name: 'Freekeh Flour', qty: 1 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Freekeh Flour Dough', qty: 2 }] },

  // Dairy
  { category: 'Shaking', name: 'Milk + Sugar → Cream', inputs: [{ name: 'Milk', qty: 1 }, { name: 'Sugar', qty: 1 }], outputs: [{ name: 'Cream', qty: 2 }] },
  { category: 'Shaking', name: 'Cream + Salt → Butter', inputs: [{ name: 'Cream', qty: 1 }, { name: 'Salt', qty: 1 }], outputs: [{ name: 'Butter', qty: 2 }] },

  // Fertilizer
  { category: 'Shaking', name: 'Inorganic Fertilizer → Byproduct Fertilizer', inputs: [{ name: 'Inorganic Fertilizer', qty: 3 }, { name: 'Leavening Agent', qty: 2 }], outputs: [{ name: 'Byproduct Fertilizer', qty: 1 }] },
  { category: 'Shaking', name: 'Byproduct Fertilizer → Organic Fertilizer', inputs: [{ name: 'Byproduct Fertilizer', qty: 1 }, { name: 'Purified Water', qty: 2 }], outputs: [{ name: 'Organic Fertilizer', qty: 1 }] },

  // Supreme Hides
  { category: 'Shaking', name: 'Fine Soft Hide → Supreme Soft Hide', inputs: [{ name: 'Fine Soft Hide', qty: 3 }, { name: 'Leather Glaze', qty: 5 }], outputs: [{ name: 'Supreme Soft Hide', qty: 1 }] },
  { category: 'Shaking', name: 'Fine Tough Hide → Supreme Tough Hide', inputs: [{ name: 'Fine Tough Hide', qty: 3 }, { name: 'Leather Glaze', qty: 5 }], outputs: [{ name: 'Supreme Tough Hide', qty: 1 }] },
  { category: 'Shaking', name: 'Fine Thick Fur → Supreme Thick Fur', inputs: [{ name: 'Fine Thick Fur', qty: 3 }, { name: 'Leather Glaze', qty: 5 }], outputs: [{ name: 'Supreme Thick Fur', qty: 1 }] },
  { category: 'Shaking', name: 'Fine Hard Hide → Supreme Hard Hide', inputs: [{ name: 'Fine Hard Hide', qty: 3 }, { name: 'Leather Glaze', qty: 5 }], outputs: [{ name: 'Supreme Hard Hide', qty: 1 }] },
  { category: 'Shaking', name: 'Fine Thin Hide → Supreme Thin Hide', inputs: [{ name: 'Fine Thin Hide', qty: 3 }, { name: 'Leather Glaze', qty: 5 }], outputs: [{ name: 'Supreme Thin Hide', qty: 1 }] },
  { category: 'Shaking', name: 'Fine Fancy Fur → Supreme Fancy Fur', inputs: [{ name: 'Fine Fancy Fur', qty: 3 }, { name: 'Leather Glaze', qty: 5 }], outputs: [{ name: 'Supreme Fancy Fur', qty: 1 }] },

  // ═══════════════════════════════════════════════════════════════════════════════
  // SIMPLE COOKING
  // ═══════════════════════════════════════════════════════════════════════════════
  { category: 'Simple Cooking', name: 'Grain + Water → Grain Juice', inputs: [{ name: 'Wheat', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Grain Juice', qty: 10 }] },
  { category: 'Simple Cooking', name: 'Barley + Water → Grain Juice', inputs: [{ name: 'Barley', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Grain Juice', qty: 10 }] },
  { category: 'Simple Cooking', name: 'Potato + Water → Grain Juice', inputs: [{ name: 'Potato', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Grain Juice', qty: 10 }] },
  { category: 'Simple Cooking', name: 'Corn + Water → Grain Juice', inputs: [{ name: 'Corn', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Grain Juice', qty: 10 }] },
  { category: 'Simple Cooking', name: 'Sweet Potato + Water → Grain Juice', inputs: [{ name: 'Sweet Potato', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Grain Juice', qty: 10 }] },
  { category: 'Simple Cooking', name: 'Grain Juice → Concentrated Grain Juice', inputs: [{ name: 'Grain Juice', qty: 3 }], outputs: [{ name: 'Concentrated Grain Juice', qty: 1 }] },
  { category: 'Simple Cooking', name: 'Concentrated → Highly Concentrated Grain Juice', inputs: [{ name: 'Concentrated Grain Juice', qty: 3 }], outputs: [{ name: 'Highly Concentrated Grain Juice', qty: 1 }] },
  { category: 'Simple Cooking', name: 'Highly Concentrated → Refined Grain Juice', inputs: [{ name: 'Highly Concentrated Grain Juice', qty: 3 }], outputs: [{ name: 'Refined Grain Juice', qty: 1 }] },

  // ═══════════════════════════════════════════════════════════════════════════════
  // SIMPLE ALCHEMY
  // ═══════════════════════════════════════════════════════════════════════════════
  { category: 'Simple Alchemy', name: 'Herb + Water → Herbal Juice', inputs: [{ name: 'Sunrise Herb', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Herbal Juice', qty: 10 }] },
  { category: 'Simple Alchemy', name: 'Silver Azalea + Water → Herbal Juice', inputs: [{ name: 'Silver Azalea', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Herbal Juice', qty: 10 }] },
  { category: 'Simple Alchemy', name: 'Fire Flake Flower + Water → Herbal Juice', inputs: [{ name: 'Fire Flake Flower', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Herbal Juice', qty: 10 }] },
  { category: 'Simple Alchemy', name: 'Dry Mane Grass + Water → Herbal Juice', inputs: [{ name: 'Dry Mane Grass', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Herbal Juice', qty: 10 }] },
  { category: 'Simple Alchemy', name: 'Silk Honey Grass + Water → Herbal Juice', inputs: [{ name: 'Silk Honey Grass', qty: 3 }, { name: 'Mineral Water', qty: 1 }], outputs: [{ name: 'Herbal Juice', qty: 10 }] },
  { category: 'Simple Alchemy', name: 'Herbal Juice → Concentrated Herbal Juice', inputs: [{ name: 'Herbal Juice', qty: 3 }], outputs: [{ name: 'Concentrated Herbal Juice', qty: 1 }] },
  { category: 'Simple Alchemy', name: 'Concentrated → Highly Concentrated Herbal Juice', inputs: [{ name: 'Concentrated Herbal Juice', qty: 3 }], outputs: [{ name: 'Highly Concentrated Herbal Juice', qty: 1 }] },
  { category: 'Simple Alchemy', name: 'HP Potion (Small) → HP Potion (Medium)', inputs: [{ name: 'HP Potion (Small)', qty: 3 }], outputs: [{ name: 'HP Potion (Medium)', qty: 1 }] },
  { category: 'Simple Alchemy', name: 'HP Potion (Medium) → HP Potion (Large)', inputs: [{ name: 'HP Potion (Medium)', qty: 3 }], outputs: [{ name: 'HP Potion (Large)', qty: 1 }] },
  { category: 'Simple Alchemy', name: 'HP Potion (Large) → HP Potion (Extra Large)', inputs: [{ name: 'HP Potion (Large)', qty: 3 }], outputs: [{ name: 'HP Potion (Extra Large)', qty: 1 }] },
  { category: 'Simple Alchemy', name: 'MP Potion (Small) → MP Potion (Medium)', inputs: [{ name: 'MP Potion (Small)', qty: 3 }], outputs: [{ name: 'MP Potion (Medium)', qty: 1 }] },
  { category: 'Simple Alchemy', name: 'MP Potion (Medium) → MP Potion (Large)', inputs: [{ name: 'MP Potion (Medium)', qty: 3 }], outputs: [{ name: 'MP Potion (Large)', qty: 1 }] },
  { category: 'Simple Alchemy', name: 'MP Potion (Large) → MP Potion (Extra Large)', inputs: [{ name: 'MP Potion (Large)', qty: 3 }], outputs: [{ name: 'MP Potion (Extra Large)', qty: 1 }] },
];
